export const copy = {
  en: {
    invited: "Together with our families",
    open: "Open your invitation",
    personal: "A little something, just for you.",
    celebrate: "WE WOULD LOVE YOU TO CELEBRATE WITH US",
    story: "Some things are meant to be.",
    programme: "A weekend to remember.",
    journey: "Make a little journey of it.",
    rsvp: "Will you join us?",
    respond: "Your RSVP",
    attending: "You’re coming",
    answered: "Your response",
    pass: "Your wedding pass",
    photos: "The moments between.",
    share: "Share a memory",
    yes: "With pleasure",
    no: "Sadly, I can’t",
    next: "A few little details",
    save: "Save our response",
    saved: "A place in our story.",
    savedDesc:
      "Your response is safely with us. You can return to this invitation to update it before the deadline.",
    update: "Update our response",
    calendar: "Add to calendar",
    directions: "Find your way",
    details: "The details",
    travel: "Travel & stay",
    contact: "Your contact details",
    meal: "What should we prepare?",
    dietary: "Anything we should know about?",
    dietHint: "Allergies or dietary requirements",
    name: "Your name",
    close: "Back to the celebration",
    gifts: "Your presence is the present.",
    uploadNote:
      "JPG, PNG or WebP, up to 10 MB. Your hosts review photos before sharing.",
    envelope: "FOR OUR FAVOURITE PEOPLE",
    day: "The day, in your pocket.",
  },
  es: {
    invited: "Junto con nuestras familias",
    open: "Abre tu invitación",
    personal: "Un pequeño detalle, solo para ti.",
    celebrate: "NOS ENCANTARÍA CELEBRAR CONTIGO",
    story: "Hay historias que están destinadas a ser.",
    programme: "Un fin de semana para recordar.",
    journey: "El viaje también es parte de la historia.",
    rsvp: "¿Nos acompañas?",
    respond: "Tu respuesta",
    attending: "Nos acompañas",
    answered: "Tu respuesta enviada",
    pass: "Tu pase de boda",
    photos: "Los pequeños momentos.",
    share: "Comparte un recuerdo",
    yes: "Con mucho gusto",
    no: "Lo siento, no puedo",
    next: "Unos pequeños detalles",
    save: "Guardar nuestra respuesta",
    saved: "Un lugar en nuestra historia.",
    savedDesc:
      "Hemos guardado tu respuesta. Puedes volver a esta invitación para actualizarla antes de la fecha límite.",
    update: "Actualizar nuestra respuesta",
    calendar: "Añadir al calendario",
    directions: "Cómo llegar",
    details: "Los detalles",
    travel: "Viaje y alojamiento",
    contact: "Tus datos de contacto",
    meal: "¿Qué te preparamos?",
    dietary: "¿Algo que debamos saber?",
    dietHint: "Alergias o necesidades alimentarias",
    name: "Tu nombre",
    close: "Volver a la celebración",
    gifts: "Tu presencia es nuestro regalo.",
    uploadNote:
      "JPG, PNG o WebP, hasta 10 MB. Los anfitriones revisarán las fotos antes de compartirlas.",
    envelope: "PARA NUESTRAS PERSONAS FAVORITAS",
    day: "Todo el día, en tu bolsillo.",
  },
};
